import * as api from './apiService';
import { getToken } from './tokenHelper';

/* ── Response types ─────────────────────────────────────────── */

export interface PlanStatus {
  is_premium: boolean;
  status: 'active' | 'canceled' | 'inactive';
  current_period_start: string | null;
  current_period_end: string | null;
}

export interface PixCheckoutResponse {
  order_id: string;
  status: string;
  amount: string;
  ticket_url: string;
  qr_code: string;
  qr_code_base64: string;
}

/** Payload sent by the Mercado Pago CardPayment brick onSubmit */
export interface CardFormData {
  token: string;
  issuer_id: string | null;
  payment_method_id: string;
  transaction_amount: number;
  installments: number;
  payment_method_option_id?: string | null;
  processing_mode?: string | null;
  payer: {
    email: string;
    identification?: { type: string; number: string };
  };
}

export interface CardCheckoutResponse {
  status: 'approved' | 'pending' | 'in_process' | 'rejected';
  payment_id: string;
  status_detail: string;
}

export interface CancelResponse {
  ok: boolean;
  subscription: PlanStatus;
}

/* ── Endpoints ──────────────────────────────────────────────── */

/**
 * GET /plans/status
 * Returns the current subscription status of the authenticated user.
 */
export async function getPlanStatus(): Promise<PlanStatus> {
  const token = await getToken();
  return api.get<PlanStatus>('/plans/status', { token });
}

/**
 * POST /plans/checkout/pix
 * Creates a Pix payment order via Mercado Pago.
 * Idempotent: repeated calls return the same open order.
 */
export async function createPixCheckout(): Promise<PixCheckoutResponse> {
  const token = await getToken();
  return api.post<PixCheckoutResponse>('/plans/checkout/pix', {}, { token });
}

/**
 * POST /plans/checkout/card
 * Processes a card payment using the token generated by the MP CardPayment brick.
 */
export async function createCardCheckout(
  formData: CardFormData,
): Promise<CardCheckoutResponse> {
  const token = await getToken();
  return api.post<CardCheckoutResponse>('/plans/checkout/card', formData, { token });
}

/**
 * POST /plans/cancel
 * Cancels the premium plan.
 * Access remains until current_period_end.
 */
export async function cancelPlan(): Promise<CancelResponse> {
  const token = await getToken();
  return api.post<CancelResponse>('/plans/cancel', {}, { token });
}
